### ISSUE TITLE
Приглашение в репозиторий 

### ISSUE THREAD

**Issue by Romankkl03** [citec-spbu/Smart-UAV-Return-GNSS-Station#1]
@sevryukov
Необходимо отправить ссылки-приглашения заново для Баранова Вадима,  Измайлова Никиты, Петровой Екатерины.

**Comment by sevryukov** [comment]
@Romankkl03 Хорошо, присылайте их GH ID.

> Необходимо отправить ссылки-приглашения заново для Баранова Вадима

Разве @VadB4r уже не имеет доступа?

**Comment by VadB4r** [comment]
Имею

**Comment by Romankkl03** [comment]
@sk7rex, @mrpeet21

**Comment by sevryukov** [comment]
Done
