### ISSUE TITLE
Получение фичей из геоподложки

### ISSUE THREAD

**Issue by Romankkl03** [citec-spbu/Smart-UAV-Return-GNSS-Station#2]
### Спринт 2
@DevDenus (Фомичев Денис)
- [x] Найти датасет с геоподложками
- [x] Найти геоподложку
- [x] Наладить связь через API к геоподложке OSM
- [x] Прорисовка карты OSM через тэги
- [x]  Выделение зданий по маске
- [x] Установка ОС на RockChip
- [x] Создание БД с эмбеддингами с геоподложки
- [x] Реализация алгоритма для поиска схожих эмбеддингов из БД
- [x] Загрузка общего пайплайна на RockChip
- [x] Посетить Геоскан и обсудить детали проекта с заказчиком
- [x] пайплайн получение эмбеддингов с камеры

**Comment by sevryukov** [comment]
@Romankkl03 где можно ознакомиться с результатами поиска датасетов с геоподложками, какие-то требования к данным предъявляются?

**Comment by Romankkl03** [comment]
https://yandex.ru/maps-api/products/tiles-api - доступ платный
https://maps.stamen.com/#terrain - нет данных со спутника
https://www.thunderforest.com/maps/ - нет данных со спутника
https://dev.2gis.ru/order/ - необходим запрос
https://www.openstreetmap.org/#map=1/38/-102 - нет данных со спутника

Нам так нужны данные со спутника и геоподложки, потому что:
1. Нужно получать схожие эмбеддинги с теми, что получили с видео
2. Нужно предварительно составить карту местности
3. Нужно вычислять расстояние между объектами для построения графа

**Comment by sevryukov** [comment]
@Romankkl03 не увидел требований к данным (снимкам) - разрешение, формат, объём и т.д.

Что-то из этого может подойти: [5 источников бесплатных спутниковых снимков](https://sovzond.ru/press-center/articles/ers/5823/)?

> Нужно предварительно составить карту местности

Карта местности это что? Если речь идёт о дорогах, к примеру, или географических объектах, то для этого не снимки нужны, а скорее соответствующие слои данных из OSM (если говорить про открытые источники).

> Нужно вычислять расстояние между объектами для построения графа

Для этого нужна привязка снимка к координатам и см. предыдущий комментарий.

**Comment by Romankkl03** [comment]
Мы посмотрели те ссылки, которые вы скинули, нам подошла только одна (только там можно получить доступ к API), однако требуется VPN, что плохо отразится на продуктивности. 
По поводу карты местности, нам скорее нужно получать схожие эмбеддинги с тем, что мы получаем с камеры (учитывая цвет, неровности поверхности...) этого можно добиться, если есть есть пикчи со спутника. Так же нужна привязка к физическим координатам. Поэтому мы и просим предоставить доступ к геоподложкам. 
Требования к картинкам:

- разрешение (минимум 2000x2000 px при масштабе до 100 метров)
- безоблачность
- городская местность
- изображения должны иметь общие сегменты(чтобы была возможность их "склеить")
- минимум 200 картинок 

Пока решили делать с OSM, но хотелось бы получить API и попробовать со снимками со спутника.

**Comment by sevryukov** [comment]
@iblekanov посмотри, пожалуйста - надо привлечь внимание заказчика.
