### ISSUE TITLE
Данные геоподложки

### ISSUE THREAD

**Issue by Romankkl03** [citec-spbu/Smart-UAV-Return-GNSS-Station#8]
Не получается получить доступ к данным геоподложки 2ГИС для использования в проекте. 

- [ ] Просим отправить им запрос на использование данных. 
Сайт для отправки запроса: https://dev.2gis.ru/order/

**Comment by sevryukov** [comment]
@Romankkl03 я правильно понимаю, что Вам нужна помощь со стороны организаторов практики?

Если да, то уточните, пожалуйста,
1. Посему необходимы именно эти данные?
2. Могут ли подойти данные OSM?
3. Как планируете использовать эти данные (где об этом можно почитать)?

@iblekanov FYI

**Comment by Romankkl03** [comment]
@sevryukov 
Либо со стороны организатора, либо со стороны заказчика. 
1. необходимы данные геоположки (снимки со спутника)
2. В данных OSM нет спутника
3. В требованиях к проекту сказано, что на вход поступают данные с геоподложки. В нашем случае, нам необходимо выделить важные фичи с геоподложки #2 для сопоставления их с фичами из видео-потока #5
